### ISSUE TITLE
连接打印机后，点击测试打印，无效果。

### ISSUE THREAD

**Issue by ALuoBo** [zhuhuitao/printer#2]
推测是与指令集有关，请问项目支持的打印机指令集是哪个？

**Comment by zhuhuitao** [comment]
1，可以加日志，看看蓝牙是否连接成功，如果蓝牙连接成功了如果没打印，可能就像您说的指令集的问题，指令集的问题，您可以在DataForSendToPrinter 类中加入您这边打印机支持的指令集，（打印机都提供有文档）。
2，另外我之前做的时候由于写的demo可能不完善，需要把蓝牙相关的权限打开。

**Comment by zhuhuitao** [comment]
另外您问的支持哪些打印指令，您可以在DataForSendToPrinter 这个类中查看，我都写有注释。如果一直无法解决，您可以留言，说明问题，我可以配合你修改。

**Comment by ALuoBo** [comment]
> 另外您问的支持哪些打印指令，您可以在DataForSendToPrinter 这个类中查看，我都写有注释。如果一直无法解决，您可以留言，说明问题，我可以配合你修改。

- 打印机指令集有一堆 ：( 每个打印集里的指令又是一堆
- 您当前的命令经过比较，确定为 ESC/POS 指令集，这个指令集是事实上的标准。我的打印机使用的是 TSPL 指令集
